/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author condondeazucar
 */
public class EnlistarPersonas extends javax.swing.JInternalFrame {

    /**
     * Creates new form EnlistarPersonas
     */
    public EnlistarPersonas() {
        initComponents();
        java.util.List<modelo.Persona> lista = new java.util.ArrayList<>();
        DefaultTableModel tbm = (DefaultTableModel) jTable1.getModel();
        tbm.setRowCount(0);
        try{
            modelo.PersonaDAO pd = new modelo.PersonaDAO();
            lista = pd.listaPersonas();
        } catch(java.sql.SQLException e){
            javax.swing.JOptionPane.showMessageDialog(null, "Ha ocurrido un error\n" + e.getMessage());
        } finally {
            for(modelo.Persona p : lista){
                String[] generos = { null, "Femenino", "Masculino" };
                String[] estadosCiviles = {
                    null,
                    "Soltero/a",
                    "Casado/a",
                    "Viudo/a",
                    "Divorciado/a",
                };
                
                Object[] arr = {    p.getId(), 
                                    p.getRut(), 
                                    p.getApellido(), 
                                    p.getNombre(), 
                                    generos[p.getGenero()], 
                                    estadosCiviles[p.getEstadoCivil()] 
                    };
                tbm.addRow(arr);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "RUT", "Apellido", "Nombre", "Genero", "Estado Civil"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange
    }//GEN-LAST:event_jTable1PropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
