/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.Persona;
import modelo.PersonaDAO;

/**
 *
 * @author condondeazucar
 */
public class ModificarPersona extends javax.swing.JInternalFrame {

    /**
     * Creates new form ModificalPersona
     */
    public ModificarPersona() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        input = new javax.swing.JTextField();
        outID = new javax.swing.JTextField();
        outNombre = new javax.swing.JTextField();
        outApellido = new javax.swing.JTextField();
        outRut = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        rbtnMasculino = new javax.swing.JRadioButton();
        rbtnFemenino = new javax.swing.JRadioButton();
        labelGenero = new javax.swing.JLabel();
        cbEstadoCivil = new javax.swing.JComboBox<>();
        btnEnviar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        input.setText("Buscar por ID");
        input.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputMouseClicked(evt);
            }
        });
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });

        outID.setEditable(false);
        outID.setText("ID");
        outID.setEnabled(false);

        outNombre.setText("Nombre");
        outNombre.setEnabled(false);

        outApellido.setText("Apellido");
        outApellido.setEnabled(false);
        outApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outApellidoActionPerformed(evt);
            }
        });

        outRut.setText("Rut");
        outRut.setEnabled(false);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        rbtnMasculino.setText("Masculino");
        rbtnMasculino.setEnabled(false);
        rbtnMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMasculinoActionPerformed(evt);
            }
        });

        rbtnFemenino.setText("Femenino");
        rbtnFemenino.setEnabled(false);
        rbtnFemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFemeninoActionPerformed(evt);
            }
        });

        labelGenero.setText("Genero");
        labelGenero.setEnabled(false);

        cbEstadoCivil.setEditable(true);
        cbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "\"<Seleccione>\"", "\"Soltero/a\"", "\"Casado/a\"", "\"Viudo/a\"", "\"Divorciado/a\"" }));
        cbEstadoCivil.setEnabled(false);
        cbEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoCivilActionPerformed(evt);
            }
        });

        btnEnviar.setText("Enviar");
        btnEnviar.setEnabled(false);
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(outRut, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outApellido, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                            .addComponent(outID, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(rbtnFemenino)
                            .addComponent(rbtnMasculino)
                            .addComponent(labelGenero))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(outID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGenero)
                    .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(rbtnMasculino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnFemenino))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void outApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outApellidoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String query = input.getText();
        try{
            PersonaDAO aux = new PersonaDAO();
            Persona p = aux.selectPersonaByID(Integer.parseInt(query));
            
            outID.setEnabled(true);
            outNombre.setEnabled(true);
            outApellido.setEnabled(true);
            outRut.setEnabled(true);
            btnEnviar.setEnabled(true);
            rbtnFemenino.setEnabled(true);
            rbtnMasculino.setEnabled(true);
            labelGenero.setEnabled(true);
            cbEstadoCivil.setEnabled(true);
            
            outID.setText(String.valueOf(p.getId()));
            outNombre.setText(p.getNombre());
            outApellido.setText(p.getApellido());
            outRut.setText(p.getRut());
            if(p.getGenero() == 1){
                rbtnFemenino.setSelected(true);
                rbtnMasculino.setSelected(false);
            }
            if(p.getGenero() == 2){
                rbtnMasculino.setSelected(true);
                rbtnFemenino.setSelected(false);
            }
            cbEstadoCivil.setSelectedIndex(p.getEstadoCivil());
        } catch (java.sql.SQLException e){
            javax.swing.JOptionPane.showMessageDialog(null, "No se ha encontrado esta persona");
        } catch (java.lang.NullPointerException e){
            javax.swing.JOptionPane.showMessageDialog(null, "No se ha podido establecer conexion con la base de datos");
        } catch (java.lang.NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(null, "La ID es un valor entero. Por favor, solo ingrese numeros.");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cbEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadoCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEstadoCivilActionPerformed

    /*
        JTextField input
    */
    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        // Does Nothing
    }//GEN-LAST:event_inputActionPerformed

    private void inputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputMouseClicked
        input.setText("");
    }//GEN-LAST:event_inputMouseClicked

    private void rbtnMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMasculinoActionPerformed
        rbtnMasculino.setSelected(true);
        rbtnFemenino.setSelected(false);
    }//GEN-LAST:event_rbtnMasculinoActionPerformed

    private void rbtnFemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFemeninoActionPerformed
        rbtnMasculino.setSelected(false);
        rbtnFemenino.setSelected(true);
    }//GEN-LAST:event_rbtnFemeninoActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        Persona p = new Persona();
        p.setApellido(outApellido.getText());
        p.setNombre(outNombre.getText());
        p.setEstadoCivil(cbEstadoCivil.getSelectedIndex());
        p.setRut(outRut.getText());
        p.setId(Integer.parseInt(outID.getText()));
        if(rbtnFemenino.isSelected()){
            p.setGenero(1);
        }
        else{
            p.setGenero(2);
        }
        
        PersonaDAO pd = new PersonaDAO();
        try{
            pd.ModificarPersonaByID(p);
            javax.swing.JOptionPane.showMessageDialog(null, "Se ha modificado con exito!");
        } catch(java.sql.SQLException e){
            javax.swing.JOptionPane.showMessageDialog(null, "No se pudo modificar el dato.\n" + e.toString());
        } catch(java.lang.Exception e){
            javax.swing.JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbEstadoCivil;
    private javax.swing.JTextField input;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JTextField outApellido;
    private javax.swing.JTextField outID;
    private javax.swing.JTextField outNombre;
    private javax.swing.JTextField outRut;
    private javax.swing.JRadioButton rbtnFemenino;
    private javax.swing.JRadioButton rbtnMasculino;
    // End of variables declaration//GEN-END:variables
}
